/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wind_ffmpeghelper_FfmpegNativeHelper */

#ifndef _Included_FFmpegNativeHelper
#define _Included_FFmpegNativeHelper
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_wind_ffmpeghelper_FfmpegNativeHelper
 * Method:    ffmpeg_init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wind_ffmpeghelper_FFmpegNativeHelper_ffmpeg_1init
  (JNIEnv *, jobject);

/*
 * Class:     com_wind_ffmpeghelper_FfmpegNativeHelper
 * Method:    ffmpeg_uninit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wind_ffmpeghelper_FFmpegNativeHelper_ffmpeg_1uninit
  (JNIEnv *, jobject);

/*
 * Class:     com_wind_ffmpeghelper_FfmpegNativeHelper
 * Method:    ffmpeg_entry
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wind_ffmpeghelper_FFmpegNativeHelper_ffmpeg_1entry
  (JNIEnv *, jobject, jint, jobjectArray strArray);

#ifdef __cplusplus
}
#endif
#endif
